#!/bin/bash
for i in $(ls *.svg)
do
  for size in $(echo "16 22 32 48 64")
  do
    file=$(echo "../pics/"$size"-actions-"$(echo $i | awk -F . '{print $1}' )".png")
    echo "Exporting "$i" to "$file
    rm -f $file
    inkscape -w $size -h $size -e $file $i > /dev/null
  done;
done;

