######################################################################
# Automatically generated by qmake (2.01a) Cs jan. 21 00:28:18 2010
######################################################################

CONFIG += qtestlib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += mytest-1.cpp

